import type MarkdownIt from 'markdown-it'

/** Set to true to enable debug logging during build */
const DEBUG = false

const HTML_TAGS = new Set([
  'a','abbr','address','area','article','aside','audio',
  'b','base','bdi','bdo','blockquote','body','br','button',
  'canvas','caption','cite','code','col','colgroup',
  'data','datalist','dd','del','details','dfn','dialog','div','dl','dt',
  'em','embed','fieldset','figcaption','figure','footer','form',
  'h1','h2','h3','h4','h5','h6','head','header','hgroup','hr','html',
  'i','iframe','img','input','ins','kbd','label','legend','li','link',
  'main','map','mark','menu','meta','meter','nav','noscript',
  'object','ol','optgroup','option','output','p','picture','pre','progress',
  'q','rp','rt','ruby','s','samp','script','section','select','slot',
  'small','source','span','strong','style','sub','summary','sup',
  'table','tbody','td','template','textarea','tfoot','th','thead',
  'time','title','tr','track','u','ul','var','video','wbr',
  'client-only','content','doc-footer','doc-sidebar',
  'mjx-container', 'mjx-assistive-mml', 'mjx-body', 'mjx-math', 'mjx-mrow', 'mjx-mi', 'mjx-mo', 'mjx-mn', 'mjx-msup', 'mjx-msub', 'mjx-mfrac', 'mjx-munder', 'mjx-mover', 'mjx-mspace', 'mjx-mtext', 'mjx-ms', 'mjx-mpadded', 'mjx-mphantom', 'mjx-menclose', 'mjx-merror',
  'math', 'mrow', 'mi', 'mo', 'mn', 'msup', 'msub', 'mfrac', 'munder', 'mover', 'munderover', 'mspace', 'mtext', 'ms', 'mpadded', 'mphantom', 'menclose', 'merror', 'mtable', 'mtr', 'mtd', 'maligngroup', 'malignmark', 'mprescripts', 'none', 'msqrt', 'mroot', 'mfenced', 'mstyle', 'semantics', 'annotation',
  'vp-code-group', 'vp-tab',
  // SVG (generated by MathJax)
  'svg','path','g','rect','circle','line','polygon','polyline','text',
  'use','defs','clippath','lineargradient','radialgradient','stop',
  'title','desc','image','pattern','mask','marker','symbol','foreignobject',
])

function looksLikeCppTemplate(inner: string): boolean {
  const trimmed = inner.trim()
  if (!trimmed) return false
  if (HTML_TAGS.has(trimmed.toLowerCase())) return false
  // Vue components use PascalCase (e.g. <ChapterNav>); C++ templates are lowercase
  if (/^[A-Z][a-zA-Z0-9]+$/.test(trimmed)) return false
  return /^[A-Za-z_][A-Za-z0-9_:,\s*&.]*(?:\.\.\.)?$/.test(trimmed)
}

function processLine(line: string): string {
  const segments = line.split(/(``[^`]*``|`[^`]*`)/)
  return segments.map((seg, i) => {
    if (i % 2 === 1) return seg
    return seg.replace(/<([^<>\n]+)>/g, (match, inner) => {
      return looksLikeCppTemplate(inner)
        ? `&lt;${inner.trim()}&gt;`
        : match
    })
  }).join('')
}

function escapeCppTemplates(src: string): string {
  const lines = src.split('\n')
  let inFence = false
  let fenceChar = ''

  return lines.map(line => {
    const fenceMatch = line.match(/^(\s*)(```+|~~~+)/)
    if (fenceMatch) {
      const marker = fenceMatch[2]
      if (!inFence) {
        inFence = true
        fenceChar = marker[0]
        return line
      }
      if (marker[0] === fenceChar && marker.length >= 3) {
        inFence = false
        fenceChar = ''
      }
      return line
    }

    if (inFence) return line
    return processLine(line)
  }).join('\n')
}

/**
 * Post-process rendered HTML: escape any remaining <...> that look like
 * C++ template syntax rather than real HTML tags.
 */
function sanitizeHtml(html: string): string {
  return html.replace(
    /<\/?([a-zA-Z][a-zA-Z0-9:-]*)([^>]*)>/g,
    (match, tag: string) => {
      if (HTML_TAGS.has(tag.toLowerCase())) return match
      // Vue components use PascalCase — skip them (C++ templates are lowercase)
      if (tag[0] === tag[0].toUpperCase() && tag[0] !== tag[0].toLowerCase()) return match
      return match.replace(/^</, '&lt;').replace(/>$/, '&gt;')
    }
    // C 聚合初始化 {…} 在正文出现会触发 Vue 的 {{ 插值解析(如 Queue q = {{0}, 0, 0, 0};)
  ).replace(/\{\{/g, '&#123;&#123;')
}

export function cppTemplateEscapePlugin(md: MarkdownIt): void {
  const originalRender = md.render.bind(md)

  md.render = function (src: string, env?: unknown): string {
    const processedSrc = escapeCppTemplates(src)
    if (DEBUG && src !== processedSrc) {
      const relPath = (env as any)?.relativePath || ''
      console.error(`[pre] ${relPath}: src changed`)
    }

    let html = originalRender(processedSrc, env)
    const sanitized = sanitizeHtml(html)
    if (DEBUG && html !== sanitized) {
      const relPath = (env as any)?.relativePath || ''
      console.error(`[post] ${relPath}: html sanitized`)
      for (let i = 0; i < html.length; i++) {
        if (html[i] !== sanitized[i]) {
          console.error(`  before: ...${html.substring(Math.max(0, i - 20), i + 30)}...`)
          console.error(`  after:  ...${sanitized.substring(Math.max(0, i - 20), i + 30)}...`)
          break
        }
      }
    }

    return sanitized
  }
}
